quarkus.datasource.db-kind=mysql
quarkus.datasource.username=property
quarkus.datasource.password=property
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/propertydb

quarkus.hibernate-orm.database.generation=update
